version: 0.2

env:
  variables:
    SLS_DEBUG: "*"
    CI: "true"
    OVERRIDE_DYNAMODB_LOCAL_ENDPOINT: "http://localhost:8000"
    OVERRIDE_S3_LOCAL_ENDPOINT: "http://localhost:8100"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd app
      - docker-compose up -d localstack

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run test:coverage

  post_build:
    commands:
      - npm run deploy:dev
      - cd static
      - APIID=$(aws apigateway get-rest-apis --query "items[?name=='dev-@@bucket-prefix@@-app-s2o'].id | [0]" | sed "s/\"//g")
      - sed -i "s/_PUT_APIID_HERE/${APIID}/g" index.html
      - aws s3 cp . s3://@@bucket-prefix@@-app-s2o --recursive --acl public-read
